###
GET http://localhost:8080/api/v1/3
Authorization: Basic {{user}} {{password}}


###
GET http://localhost:8080/management/api/v1/students
Authorization: Basic {{user}} {{password}}


###
POST http://localhost:8080/management/api/v1/students
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

{
  "studentName": "lashawnaij3"
}


###
PUT http://localhost:8080/management/api/v1/students/1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

{
  "studentName": "lashawnaij3"
}


###
DELETE http://localhost:8080/management/api/v1/students/1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}
